apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: arangobackuppolicies.database.arangodb.com
spec:
  group: database.arangodb.com
  names:
    kind: ArangoBackupPolicy
    listKind: ArangoBackupPolicyList
    plural: arangobackuppolicies
    shortNames:
    - arangobackuppolicy
    - arangobp
    singular: arangobackuppolicy
  scope: Namespaced
  version: v1alpha
  subresources:
    status: {}
  
---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: arangobackups.database.arangodb.com
spec:
  group: database.arangodb.com
  names:
    kind: ArangoBackup
    listKind: ArangoBackupList
    plural: arangobackups
    shortNames:
    - arangobackup
    singular: arangobackup
  scope: Namespaced
  version: v1alpha
  subresources:
    status: {}