
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Deployment.OperatorDeploymentName }}
  namespace: {{ .Deployment.Operator.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ .Deployment.OperatorDeploymentName }}
    spec:
      containers:
      - name: operator
        imagePullPolicy: {{ .ImagePullPolicy }}
        image: {{ .Image }}
        args:
          - --operator.deployment
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: metrics
          containerPort: 8528
        livenessProbe:
          httpGet:
            path: /health
            port: 8528
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready/deployment
            port: 8528
          initialDelaySeconds: 5
          periodSeconds: 10
