apiVersion: v1
kind: Service
metadata:
  name: {{ .Deployment.OperatorDeploymentName }}
  namespace: {{ .Deployment.Operator.Namespace }}
  labels:
    name: {{ .Deployment.OperatorDeploymentName }}
    app: arango-deployment-operator
spec:
  ports:
  - name: server
    port: 8528
    protocol: TCP
    targetPort: 8528
  selector:
    name: {{ .Deployment.OperatorDeploymentName }}
    app: arango-deployment-operator
    role: leader
  type: {{ .Deployment.Operator.ServiceType }}
