
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .DeploymentReplication.OperatorDeploymentName }}
  namespace: {{ .DeploymentReplication.Operator.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ .DeploymentReplication.OperatorDeploymentName }}
        app: arango-deployment-replication-operator
    spec:
      containers:
      - name: operator
        imagePullPolicy: {{ .ImagePullPolicy }}
        image: {{ .Image }}
        args:
          - --operator.deployment-replication
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: metrics
          containerPort: 8528
        livenessProbe:
          httpGet:
            path: /health
            port: 8528
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready/deployment-replication
            port: 8528
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
