
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Storage.OperatorName }}
  namespace: {{ .Storage.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ .Storage.OperatorName }}
    spec:
      containers:
      - name: operator
        imagePullPolicy: {{ .ImagePullPolicy }}
        image: {{ .Image }}
        args:
        - --operator.storage
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
