## Service accounts
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Storage.Operator.Namespace }}
  name: {{ .Storage.Operator.ServiceAccountName }}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Storage.OperatorDeploymentName }}
  namespace: {{ .Storage.Operator.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ .Storage.OperatorDeploymentName }}
    spec:
      serviceAccountName: {{ .Storage.Operator.ServiceAccountName }}
      containers:
      - name: operator
        imagePullPolicy: {{ .ImagePullPolicy }}
        image: {{ .Image }}
        args:
        - --operator.storage
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: metrics
          containerPort: 8528
        livenessProbe:
          httpGet:
            path: /health
            port: 8528
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready/storage
            port: 8528
          initialDelaySeconds: 5
          periodSeconds: 10
      