{{ .Storage.FilterStart }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Storage.OperatorDeploymentName }}
  namespace: {{ .Storage.Operator.Namespace }}
  labels:
    name: {{ .Storage.OperatorDeploymentName }}
    app: arango-storage-operator
spec:
  ports:
  - name: server
    port: 8528
    protocol: TCP
    targetPort: 8528
  selector:
    name: {{ .Storage.OperatorDeploymentName }}
    app: arango-storage-operator
    role: leader
  type: {{ .Storage.Operator.ServiceType }}

{{ .Storage.FilterEnd }}
