## storage/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: arango-deployment-operator
rules:
- apiGroups:
  - storage.arangodb.com
  resources:
  - arangolocalstorages
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  - persistentvolumeclaims
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - "*"
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - "*"

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: arango-deployment-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: arango-deployment-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: default

---

## storage/deployment.yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: arango-storage-operator
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: arango-storage-operator
    spec:
      containers:
      - name: operator
        imagePullPolicy: IfNotPresent
        image: ewoutp/arangodb-operator@sha256:51a122f8b36cb26f181dd1ffdddae6cb3fb5a4def4709c3ea123744a557cbe08
        args:
        - --operator.storage
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

