## rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: arango-operator
rules:
- apiGroups:
  - database.arangodb.com
  resources:
  - arangodeployments
  verbs:
  - "*"
- apiGroups:
  - storage.arangodb.com
  resources:
  - arangolocalstorages
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumes
  - persistentvolumeclaims
  - events
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs:
  - "*"
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - "*"

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: arango-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: arango-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: default

---

## deployment.yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: arango-operator
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: arango-operator
    spec:
      containers:
      - name: arangodb-operator
        imagePullPolicy: IfNotPresent
        image: arangodb/arangodb-operator@sha256:08451a73c330e1a3b6f18ba47d7b14f7ce7590387f01b70290d532a244250d58
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

