apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: arangodb-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: arangodb-operator
    spec:
      containers:
      - name: arangodb-operator
        imagePullPolicy: IfNotPresent
        image: arangodb/arangodb-operator:latest
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name