
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .OperatorName }}
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ .OperatorName }}
    spec:
      containers:
      - name: arangodb-operator
        imagePullPolicy: {{ .ImagePullPolicy }}
        image: {{ .OperatorImage }}
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
